require 'fileutils'
require 'pathname'


Rake::FileList.new("src/labs/*").each do |directory|
    lab_id = Pathname.new(directory).basename.to_s
    mode = "development"

    desc "Build lab #{lab_id}"
    task lab_id do
        puts "Building #{lab_id}"
        system({ 'LAB' => lab_id }, "npm run build:#{mode}") or abort "Failed to build #{lab_id}"
    end
end
