require 'pathname'

def find_git_root
    current = Pathname.pwd

    while not current.join('.git').exist?
        current = current.parent
    end

    current
end

def find_dist_directory
    result = find_git_root.join('dist')

    unless result.exist?
        result.mkpath
    end

    result
end


texs = Dir['*.tex'].select do |entry|
    not entry.start_with? 'aux-'
end

pdfs = texs.map do |tex|
    tex.ext '.pdf'
end

task default: [ :pdfs ]

texs.zip(pdfs).each do |tex, pdf|
    desc "Generate #{pdf}"
    file pdf => [ tex ] do |x|
        2.times { sh "pdflatex #{entry}" }
    end
end

desc "Generate pdfs"
task pdfs: pdfs

desc "Copy files to dist"
task dist: pdfs do
    dist = find_dist_directory

    pdfs.each do |pdf|
        cp pdf, dist
    end
end